kavishdevar/librepods

- android/app/src/main/java/me/kavishdevar/aln/BatteryWidget.kt
- android/app/src/main/java/me/kavishdevar/aln/services/AirPodsService.kt
Update `AirPodsService.kt` and `BatteryWidget.kt` to retain and display the last received battery levels when the case or bud gets disconnected.
* **AirPodsService.kt**
- Comment out the condition that sets battery levels to an empty string if the status is `BatteryStatus.DISCONNECTED`.
* **BatteryWidget.kt**
- Comment out the condition that sets battery levels to an empty string if the status is `BatteryStatus.DISCONNECTED`.
> Show last saved battery in notification

- linux/main.cpp
It's easier to read the name instead of a number.
Showing the correct battery level when only 1 airpod is connected also slippen in this branch, idk how this happended.
> [Linux] Use a enum to control the noise control mode

- linux/CMakeLists.txt
- linux/airpods_packets.h
- linux/battery.hpp
- linux/main.cpp
This PR addresses an issue where the battery levels for the left and right AirPods were sometimes incorrectly switched. The problem stemmed from a hardcoded assumption in the previous code: it assumed the left AirPod was always the first in the data, when in fact, the primary AirPod (which could be either left or right) is reported first. This led to misassigned levels when the primary AirPod didn’t align with the hardcoded order. The new Battery class resolves this by dynamically identifying the components based on the actual data provided, eliminating the switching issue.
> [Linux] Add Battery Class and Fix Battery Level Assignment

- linux/main.cpp
With only 1 airpod, it sometimes switched between the modes multiple times (@kavishdevar, you also reported this). This should fix it (at least it never occurred afterwards for me)
> [Linux] Fix noise control switches multiple times

- linux/BatteryIndicator.qml
- linux/CMakeLists.txt
- linux/Main.qml
- linux/battery.hpp
- linux/main.cpp
Looks like this now, a improvement I would say (compared to plain text)
This also adds following new functionality:
- Case battery level
- Charging indication for the pods and case
> [Linux] Add battery indicator

- android/app/src/main/java/me/kavishdevar/aln/utils/RadareOffsetFinder.kt
- root-module/customize.sh
Was stored on Hetzner beforehand which is not future-proof.
> Change radare2 download URL to GitHub releases

- linux/Main.qml
- linux/airpods_packets.h
- linux/ble/blescanner.cpp
- linux/main.cpp
This PR adds following features:
> [Linux] CA state parsing, robuster handshake, persistent window

- linux/BluetoothMonitor.cpp
- linux/BluetoothMonitor.h
- linux/CMakeLists.txt
- linux/SegmentedControl.qml
- linux/main.cpp
By watching the bluz dbus, we now have proper disconnection detection.
The previous code did not work, for l2cap sockets, Qt's disconnected event isn't emitted reliably.
This code even triggers when we disable bluetooth.
> [Linux] Implement proper disconnection detection

- AAP Definitions.md
- Proximity Pairing Message.md
- linux/ble/blemanager.cpp
> Add more documentation

- linux/BluetoothMonitor.cpp
- linux/BluetoothMonitor.h
- linux/Main.qml
- linux/main.cpp
For me the old method with QBluetoothDeviceDiscoveryAgent the connecting was pretty unstable.
It was disconnecting after a short amount of time, always. Since we already rely on BlueZ (only supported backend in Qt for Linux), I use the bluez dbus api to check for connected/disconnected devices.
Our Qt code than only connects to the service, not the device itself.
With this change I noticed a improvement in the time it takes for the app to connect to the airpods.
It's a pretty big change, and I wanna know what you think about it (@kavishdevar). I only noticed improvements. 
Upsides I know of:
- Improved connection speed
- Improved connection reliability
- Reduced resource usage (for my debug build, CPU usage not even measurable, RAM 102.4 MiB)
Possible downsides:
- App doesn't auto-connect …
> [Linux] Improve connection stability

- linux/Main.qml
- linux/main.cpp
I like to start this program when connecting to my AirPods and it isn't necessary for me to have the window pop up. Therefore, using the --hide flag when starting the program will hide the window on startup.
This could also be a configuration option (e.g. 'Start minimized') but I went with the CLI flag for simplicity for now. However, if this is a more viable option (and it may be better in the future), I can implement this as an option in the settings instead.
> [Linux] Add CLI flag to hide the window on startup

- linux/mediacontroller.cpp
- linux/mediacontroller.h
Should fix #107, needs testing (works for me)
Should work on pipewire and pulseaudio systems.
> [Linux] Dynamically find device sink name

- linux/Main.qml
- linux/main.cpp
- linux/trayiconmanager.cpp
- linux/trayiconmanager.h
This pull request would add additional functionality and quality of life enhancements to the Linux application:
- Allows for an existing app instance to be reopened from the app tray to the main app menu or settings menu
- Add separators between different options in tray to improve clarity
- Add detection for existing app instances and the ability for a duplicate instance to trigger a reopening of the original app instance instead of spinning up a new instance
This improves functionality for an end user by adding in expected responses to app interactions.
Edit:
Additional changes made since original pull request:
- Add error handling for socket and server
- Use environment variable instead of preprocessor to detect 
- Clear variable on original instance quitting
- Proper handling in case …
> [Linux] Add seperators to tray, add tray option to reopen app and settings, prevent duplicate instances of app from being opened

- linux/CMakeLists.txt
- linux/README.md
- linux/ble/CMakeLists.txt
- linux/main.cpp
Hi! I hope there is no critical reason to require Qt 6.5 as the minimum version. Debian 12 still has Qt 6.4 in its repositories, so I patched this (absolutely great) app to work with it.
AFAICT, the only missing feature in Qt 6.4 was `QQmlApplicationEngine::loadFromModule`, which was introduced in 6.5. I replaced it with an older but equivalent approach to achieve the same functionality.
In the second commit, I updated the README and added an apt command with necessary Debian dependencies.
Tested on Debian 12 with Qt 6.4.2, everything works OK so far.
> [Linux] Use Qt 6.4 for compatibility with Debian Stable

- linux/CMakeLists.txt
- linux/main.cpp
- linux/media/mediacontroller.cpp
- linux/media/mediacontroller.h
- linux/media/playerstatuswatcher.cpp
- linux/media/playerstatuswatcher.h
Replaces the need for playerctl, see https://github.com/kavishdevar/librepods/issues/125#issuecomment-2884548188
> [Linux] Replace `playerctl`

- linux/README.md
Hey!
While building Librepods, I've noticed some errors in the Linux readme, as well places for improvement. 
Changes:
* Added qt development header list for Fedora
* Added openssl development header dependency (this is bundled in the openssl package on Arch, but not in most other distros)
* `PHONE_MAC_ADDRESS` is no longer a build-time constant, but an environment variable
* The build target is `librepods`, not `applinux`
I've separated each change into a commit of it's own so you can easily cherry-pick the changes you want to apply if you don't want to set some.
Thank you for this project, hope this PR is welcome :smile:
> Fixes and improvements to the Linux readme

- linux/logger.h
- linux/main.cpp
**old:**
```
airpodsApp:  Primary Pod: Battery::Component::Left 
airpodsApp:  Secondary Pod: Battery::Component::Right 
airpodsApp:  Battery status:  "Left: 87%, Right: 88%, Case: 0%" 
````
**new:**
```
Librepods:  Primary Pod: Battery::Component::Left 
Librepods:  Secondary Pod: Battery::Component::Right 
Librepods:  Battery status:  "Left: 87%, Right: 88%, Case: 0%" 
````
> [Linux] chore: change logging name airpodsApp -> Librepods

- linux/Main.qml
- linux/main.cpp
When the environment variable "PHONE_MAC_ADDRESS" is not set:
<br/><br/><br/>
Default mac:
<br/><br/><br/>
When mac is set (still editable):
> [Linux] Let users edit Phone bluetooth MAC via GUI

- android/app/src/main/java/me/kavishdevar/librepods/utils/AACPManager.kt
- linux/airpods_packets.h
Thank you @gheinzer for discovering the problem!
This PR adds doc and fixes the issues with airpods occasionally jumping to random volumes (#27).
> android,linux: update feature flags packet data byte to remove adaptive volume

- linux/main.cpp
After a system reboot, **AirPods microphone** is detected, but the **audio output (A2DP sink) is not available**. This occurs because the Bluetooth connection is automatically restored by the system, but the **A2DP audio profile** is not activated, leaving only the **HFP/HSP profile** active (microphone only).
---
The solution is to add **A2DP profile activation** in three key scenarios:
1.  **On system wake-up**: Checks if AirPods are already connected and re-activates the A2DP profile.
2.  **On BlueZ device connection**: Activates the A2DP profile when AirPods are detected as connected via **BlueZ** (happens after reboot).
3.  **On app startup**: Activates the A2DP profile for already connected AirPods found during initialization.
---
| Category | Detail |
| :--- | :--- |
| **Platform** …
> Fix: Activate A2DP audio profile for AirPods after system reboot on Linx

- linux/media/mediacontroller.cpp
- linux/media/mediacontroller.h
This PR improves upon the earlier fix in PR #212, which handled A2DP activation timing but didn't address cases where the profile was completely unavailable due to WirePlumber's discovery timing issues. Also might fix #205.
After a **system reboot** or **Bluetooth service restart**, WirePlumber (PipeWire's session manager) often fails to properly discover **A2DP** (Advanced Audio Distribution Profile) audio profiles for Bluetooth devices like **AirPods**.
- Only **HSP/HFP** (Headset/Hands-Free Profile) appears in available profiles
- A2DP profile is completely missing from the device card (not just inactive)
- Because of caching of the A2DP profile i needed to initially select **HSP/HFP** to get the audio source again
- Manual restart of WirePlumberis required to fix
This is probably a …
> Auto-restart WirePlumber when A2DP profile is unavailable

- linux/media/mediacontroller.cpp
- linux/media/mediacontroller.h
- linux/media/pulseaudiocontroller.cpp
fixes #207 
note: this only works if the browser shows two instances for multiple media sources. playing two youtube videos in two separate tabs in Firefox exposed only one instance of media player which will not result in all media sources paused. Something I can't fix. But now, it will only resume the services it has paused not just the first one.
> linux: add support for multiple media players

- linux/README.md
Add WirePlumber AVRCP configuration documentation - #223
> docs: add troubleshooting section for media controls not working
